### ISSUE TITLE
`schema.conflicts` does not accept a list as documented

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcalot.github.io#38]
## Describe the bug

The documentation for `schema.conflicts` says "specifies a list of fields that cannot be used together with the current field," but the input expected is a string, not a list.

If it does accept a list as a string, is this space-separated or comma-separated?

https://arcalot.io/arcaflow/plugins/python/data-model/#annotations-for-validation-and-metadata

**Comment by jdowni000** [comment]
I have a [pr](https://github.com/arcalot/arcalot.github.io/pull/55) submitted.
