### ISSUE TITLE
Document foreach loop

### ISSUE THREAD

**Issue by janosdebugs** [arcalot/arcalot.github.io#45]
## Please describe what you would like to see in this project

Document the foreach loop once arcalot/arcaflow-engine#71 is merged. A quick summary is available in the [README](https://github.com/arcalot/arcaflow-engine/pull/71/files#diff-a2c70a3110de0228471189cb05d311cffc582162426095c00f4b2c115b8508d0)

**Comment by dustinblack** [comment]
jira test
